### ISSUE TITLE
Lookup pixel size from metadata

### ISSUE THREAD

**Issue by HorstmannA** [DiamondLightSource/python-murfey#110]
Take pixel size from microscope config or from the magnification in metadata.

**Comment by HorstmannA** [comment]
Kyle Morris has a lookup table ready for this

**Comment by HorstmannA** [comment]
`# Create a dataframe of Krios calibrated magnified pixel sizes and equipment parameters
# Optmal dose for Falcon 4 is 3-6 e/px/s, for the Falcon 4i is 7 e/px/s
magTableData = [{'ID':'GLACIOS-9953831', '#name' : 'GlcsII', 'number' : '2', 'mXX' : 'm12', 'camera' : 'F4i', 'cameraWpx' : '4096', 'cameraHpx' : '4096', \
            'optimalDose' : '4.5', 'serial' : '9953831', 'PC' : 'GLACIOS-9953831', '120000' : '1.192', '150000' : '0.930'}, \
            {'ID':'ARCTICA52203594', '#name' : 'Talos', 'number' : '1', 'mXX' : 'm04', 'camera' : 'K3', 'cameraWpx' : '5760', 'cameraHpx' : '4092', \
            'optimalDose' : '15', 'serial' : '3594', 'PC' : 'ARCTICA52203594', '63000' : '1.315', '79000' : '1.049', '100000' : '0.819', '130000' : '0.640', '165000' : '0.497'}, \
            {'ID':'TITAN52334190', '#name' : 'Krios1', 'number' : '1', 'mXX' : 'm02', 'camera' : 'K3', 'cameraWpx' : '5760', 'cameraHpx' : '4092', \
            'optimalDose' : '15', 'serial' : '3419', 'PC' : 'TITAN52334190', '64000' : '1.350', '81000' : '1.072', '105000' : '0.831', '130000' : '0.653', '165000' : '0.513'}, \
            {'ID':'TITAN52334150', '#name' : 'Krios2', 'number' : '2', 'mXX' : 'm03', 'camera' : 'K3', 'cameraWpx' : '5760', 'cameraHpx' : '4092', \
            'optimalDose' : '15', 'serial' : '3415', 'PC' : 'TITAN52334150', '64000' : '1.350', '81000' : '1.072', '105000' : '0.831', '130000' : '0.653', '165000' : '0.513'}, \
            {'ID':'TITAN52335130', '#name' : 'Krios3', 'number' : '3', 'mXX' : 'm06', 'camera' : 'F4i', 'cameraWpx' : '4096', 'cameraHpx' : '4096', \
            'optimalDose' : '7', 'serial' : '3513', 'PC' : 'TITAN52335130', '85000' : '1.501', '105000' : '1.171', '130000' : '0.921', '165000' : '0.723', '215000' : '0.576'}, \
            {'ID':'TITAN52336320', '#name' : 'Krios4', 'number' : '4', 'mXX' : 'm07', 'camera' : 'K3', 'cameraWpx' : '5760', 'cameraHpx' : '4092', \
            'optimalDose' : '15', 'serial' : '3632', 'PC' : 'TITAN52336320', '54000' : '1.630', '64000' : '1.340', '81000' : '1.060', '105000' : '0.829', '130000' : '0.651', '165000' : '0.508'}]
magDfTable = pd.DataFrame(magTableData)`

**Comment by HorstmannA** [comment]
Kyle's thoughts:
-probably more robust to look up mag in metadata and then calibrated pixel size from this table 
-not all magnifications have pixel size calibrations, though not impossible, it is unlikely other mags would be used by users, especially on the krioses
-I think having this right sooner rather than later is a good move, especially if pixel sizes for sessions start going into databases or log files user might one day look through 
Happy to discuss. Cheers

**Comment by d-j-hatton** [comment]
I think I'm going to tackle this one along with #104. Any objections?

**Comment by HorstmannA** [comment]
No problem
