### ISSUE TITLE
Need to fill in `movieFullPath` and `createdTimeStamp` columns properly in `Movie` table

### ISSUE THREAD

**Issue by d-j-hatton** [DiamondLightSource/python-murfey#137]

**Comment by HorstmannA** [comment]
Add the timestamp and movie path parameters [here](https://github.com/DiamondLightSource/python-murfey/blob/c8f890a0966dd152859c0abf7f0593c8db31eecd/src/murfey/server/api.py#L211)
And modify the [recipe](https://gitlab.diamond.ac.uk/scisoft/zocalo/-/blob/master/recipes/em-tomo-preprocess.json) to reflect

**Comment by HorstmannA** [comment]
I've added the recipe changes [here](https://gitlab.diamond.ac.uk/scisoft/zocalo/-/merge_requests/79) but won't merge until the changes to Murfey are deployed as I suspect it may break.
