### ISSUE TITLE
Context class in 'murfey.client.context' looking for non-existent entry point

### ISSUE THREAD

**Issue by tieneupin** [DiamondLightSource/python-murfey#399]
https://github.com/DiamondLightSource/python-murfey/blob/ba6e694e67497d69f8b8ee56b95d295f3533d3e2/src/murfey/client/context.py#L44

The group `"murfey.post_transfer_hooks"` doesn't exist in the list of available entry points in the `pyproject.toml` file.

**Comment by stephen-riggs** [comment]
It's true that these aren't present in the `pyproject.toml`, but they can be present in external packages. In particular, for DLS there are hooks in the `murfey_dls_extras` repository which are picked up by this entry point search. If no external packages are present, then this loop will just be skipped.
